### ISSUE TITLE
Set Magister/core/libs/Leerlingen.php to private

### ISSUE THREAD

**Issue by MarcusTalbotNL** [skimmet/Magister#1]
This should probably be set to private, because of privacy reasons.

**Comment by skimmet** [comment]
Pretty much all of this information is outdated. Besides this information is just names. My school doesn't use those Id's anymore.

**Comment by MarcusTalbotNL** [comment]
It's not about being able to still use the ID's. Unless you have explicit permission from the people in the list to save this data, you are actually in violation of the Wbp (Wet bescherming persoonsgegevens), which could give you a lot of trouble. So again, I advice you to delete the data, or at least close off the file.
